version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
commands:
  pre-built-branch:
    steps:
      - run:
          name: Deploy -built branch to github.
          command: |
            /bin/bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
  build-base-composer:
      steps:
      - run:
          name: Install composer inside root directory
          command: composer update --working-dir=./ -o -n
  run-liniting:
    steps:
      - run:
          name: Install composer inside theme
          command: composer --working-dir=./ php:lint
jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers
    steps:
      - checkout
      - build-base-composer
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  deploy:
    docker:
      - image: cimg/php:8.2-browsers
    steps:
      - attach_workspace:
          at: ./
      - checkout
      - pre-built-branch
workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
